kibana:
  image: kibana

  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch
  volumes:
    - "$PWD/esdata:/usr/share/elasticsearch/data"

nginx:
  image: nginx
  ports:
    - "433:443"
    - "9200:9200"
  links:
    - kibana
    - elasticsearch
  volumes:
    - "$PWD/certificate.crt:/etc/nginx/ssl/certificate.crt"
    - "$PWD/certificate.key:/etc/nginx/ssl/certificate.key"
    - "$PWD/kibana.htpasswd:/etc/nginx/conf.d/kibana.htpasswd"
    - "$PWD/default.conf:/etc/nginx/conf.d/default.conf"
